title: My Dad Pays For My Travels
email: akashzsuresh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My personal travel blog. A place, where I pen down my memories and pin down my photographs.
permalink: ':title/'
baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Akash Suresh # add your name
author-pic: akash-face.jpg
about-author: My name is Akash Suresh. I’m a full-time adventure travel blogger and photographer who’s been exploring the world.

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: akash-suresh # Add your Github handle
twitter: '@akashsuresh96' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: mydadpaysformytravels # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
